export const questions = [
  {
    id: 435,
    question:
      'In order to add a new column to an existing table in SQL, which command do we need to use?',
    description: null,
    answers: {
      answer_a: 'MODIFY TABLE',
      answer_b: 'ALTER COLUMNS',
      answer_c: 'ALTER TABLE',
      answer_d: 'EDIT TABLE',
      answer_e: null,
      answer_f: null,
    },
    multiple_correct_answers: 'false',
    correct_answers: {
      answer_a_correct: 'false',
      answer_b_correct: 'false',
      answer_c_correct: 'true',
      answer_d_correct: 'false',
      answer_e_correct: 'false',
      answer_f_correct: 'false',
    },
    correct_answer: 'answer_a',
    explanation: null,
    tip: null,
    tags: [
      {
        name: 'MySQL',
      },
    ],
    category: 'SQL',
    difficulty: 'Medium',
  },
  {
    id: 991,
    question: 'JavaScript is the same as Java.',
    description: null,
    answers: {
      answer_a: 'False',
      answer_b: 'True',
      answer_c: null,
      answer_d: null,
      answer_e: null,
      answer_f: null,
    },
    multiple_correct_answers: 'false',
    correct_answers: {
      answer_a_correct: 'true',
      answer_b_correct: 'false',
      answer_c_correct: 'false',
      answer_d_correct: 'false',
      answer_e_correct: 'false',
      answer_f_correct: 'false',
    },
    correct_answer: 'answer_a',
    explanation: null,
    tip: null,
    tags: [
      {
        name: 'JavaScript',
      },
    ],
    category: 'Code',
    difficulty: 'Easy',
  },
  {
    id: 754,
    question: 'Which command will duplicate each line in a file?',
    description: null,
    answers: {
      answer_a: "sed 'p' < filename",
      answer_b: "sed 'd' < filename",
      answer_c: "cp 'p' < filename",
      answer_d: "cp 'd' < filename",
      answer_e: "cat 'p' < filename",
      answer_f: "cat 'd' < filename",
    },
    multiple_correct_answers: 'false',
    correct_answers: {
      answer_a_correct: 'true',
      answer_b_correct: 'false',
      answer_c_correct: 'false',
      answer_d_correct: 'false',
      answer_e_correct: 'false',
      answer_f_correct: 'false',
    },
    correct_answer: 'answer_a',
    explanation: null,
    tip: null,
    tags: [
      {
        name: 'BASH',
      },
      {
        name: 'Linux',
      },
    ],
    category: 'Linux',
    difficulty: 'Hard',
  },
  {
    id: 589,
    question: 'What are the three classes of errors that can occur in PHP?',
    description: null,
    answers: {
      answer_a: 'notices',
      answer_b: 'fatal errors',
      answer_c: 'warnings',
      answer_d: 'All of the mentioned',
      answer_e: null,
      answer_f: null,
    },
    multiple_correct_answers: 'false',
    correct_answers: {
      answer_a_correct: 'false',
      answer_b_correct: 'false',
      answer_c_correct: 'false',
      answer_d_correct: 'true',
      answer_e_correct: 'false',
      answer_f_correct: 'false',
    },
    correct_answer: 'answer_a',
    explanation: null,
    tip: null,
    tags: [
      {
        name: 'PHP',
      },
    ],
    category: 'Code',
    difficulty: 'Medium',
  },
  {
    id: 875,
    question:
      "If the Plesk server can't run Docker locally, you can still connect to a remote Docker server to manage containers. You'll need:",
    description: null,
    answers: {
      answer_a: 'A virtuozzo 6 container',
      answer_b: 'One separate ready-to-code environment',
      answer_c: 'A Windows Server',
      answer_d: 'The Plesk Docker extension',
      answer_e: null,
      answer_f: null,
    },
    multiple_correct_answers: 'false',
    correct_answers: {
      answer_a_correct: 'false',
      answer_b_correct: 'false',
      answer_c_correct: 'false',
      answer_d_correct: 'true',
      answer_e_correct: 'false',
      answer_f_correct: 'false',
    },
    correct_answer: null,
    explanation: null,
    tip: null,
    tags: [
      {
        name: 'Docker',
      },
    ],
    category: 'Docker',
    difficulty: 'Easy',
  },
  {
    id: 174,
    question: 'You can define and run multiple Docker containers using:',
    description: null,
    answers: {
      answer_a: 'Docker Swarn',
      answer_b: 'Docker Hub',
      answer_c: 'Docker Cluster',
      answer_d: 'Docker Cloud',
      answer_e: null,
      answer_f: null,
    },
    multiple_correct_answers: 'false',
    correct_answers: {
      answer_a_correct: 'true',
      answer_b_correct: 'false',
      answer_c_correct: 'false',
      answer_d_correct: 'false',
      answer_e_correct: 'false',
      answer_f_correct: 'false',
    },
    correct_answer: 'answer_a',
    explanation: null,
    tip: null,
    tags: [
      {
        name: 'Docker',
      },
    ],
    category: 'Docker',
    difficulty: 'Easy',
  },
  {
    id: 543,
    question: 'What is cite tag in HTML5?',
    description: null,
    answers: {
      answer_a: '<cite title"value">Some Text Here</cite>',
      answer_b: '<cite title:"value">Some Text Here</cite>',
      answer_c: '<cite title="value">Some Text Here</cite>',
      answer_d: null,
      answer_e: null,
      answer_f: null,
    },
    multiple_correct_answers: 'false',
    correct_answers: {
      answer_a_correct: 'false',
      answer_b_correct: 'false',
      answer_c_correct: 'true',
      answer_d_correct: 'false',
      answer_e_correct: 'false',
      answer_f_correct: 'false',
    },
    correct_answer: 'answer_a',
    explanation: null,
    tip: null,
    tags: [
      {
        name: 'HTML',
      },
    ],
    category: 'Code',
    difficulty: 'Easy',
  },
  {
    id: 209,
    question: 'UPDATE keyword is used for:',
    description: null,
    answers: {
      answer_a: 'to create database elements',
      answer_b: 'to change data',
      answer_c: 'to manage users',
      answer_d: 'to select data',
      answer_e: null,
      answer_f: null,
    },
    multiple_correct_answers: 'false',
    correct_answers: {
      answer_a_correct: 'false',
      answer_b_correct: 'true',
      answer_c_correct: 'false',
      answer_d_correct: 'false',
      answer_e_correct: 'false',
      answer_f_correct: 'false',
    },
    correct_answer: 'answer_a',
    explanation: null,
    tip: null,
    tags: [
      {
        name: 'MySQL',
      },
    ],
    category: 'SQL',
    difficulty: 'Easy',
  },
  {
    id: 434,
    question: 'Which of the following statements is NOT true for views in SQL?',
    description: null,
    answers: {
      answer_a:
        'Select statement used in the view definition cannot include ORDER BY clause.',
      answer_b: 'A view contains a copy of the data',
      answer_c: 'A view drives its data from the base tables(s)',
      answer_d:
        'A view is updatable if it has been defined from a single relation',
      answer_e: null,
      answer_f: null,
    },
    multiple_correct_answers: 'false',
    correct_answers: {
      answer_a_correct: 'false',
      answer_b_correct: 'true',
      answer_c_correct: 'false',
      answer_d_correct: 'false',
      answer_e_correct: 'false',
      answer_f_correct: 'false',
    },
    correct_answer: 'answer_a',
    explanation: null,
    tip: null,
    tags: [
      {
        name: 'MySQL',
      },
    ],
    category: 'SQL',
    difficulty: 'Medium',
  },
  {
    id: 662,
    question:
      'Which command can give first found difference between two file after comparing?',
    description: null,
    answers: {
      answer_a: 'diff',
      answer_b: 'cmp',
      answer_c: 'Common',
      answer_d: 'stat',
      answer_e: null,
      answer_f: null,
    },
    multiple_correct_answers: 'false',
    correct_answers: {
      answer_a_correct: 'false',
      answer_b_correct: 'true',
      answer_c_correct: 'false',
      answer_d_correct: 'false',
      answer_e_correct: 'false',
      answer_f_correct: 'false',
    },
    correct_answer: 'answer_a',
    explanation: null,
    tip: null,
    tags: [
      {
        name: 'BASH',
      },
    ],
    category: 'Linux',
    difficulty: 'Easy',
  },
]
